title: No Money To Cultivate Immortality
description: Unofficial Fan Translation
url: "https://thundergod95.github.io"
baseurl: "/nmtci"

defaults:
    - scope:
          path: "translations"
      values:
          layout: "chapter"

markdown: kramdown
permalink: pretty

exclude:
    - scripts
    - README.md
    - LICENSE
    - bundled
    - assets/glossary.json
    - assets/glossary-schema.json
